AllCops:
  # Show full cop name when failing, making it easier to ignore if necessary
  DisplayCopNames: true
  # Links to the style guide with reasoning behind cop on failure
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
